apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: App-1
  labels:
    f5cr: "true"
spec:
  host: app1.f5demo.cloud
  tlsProfileName: app1-tls
  virtualServerAddress: "10.1.10.10"
  virtualServerName: "App-1"
  pools:
  - path: /
    service: svc-app1
    servicePort: 80
    monitor:
      type: http
      send: "GET /rn"
      recv: ""
      interval: 10
      timeout: 10
  - path: /pay
    service: svc-app2
    servicePort: 80
    monitor:
      type: http
      send: "GET /rn"
      recv: ""
      interval: 10
      timeout: 10
  - path: /portal
    service: svc-app3
    servicePort: 80
    monitor:
      type: http
      send: "GET /rn"
      recv: ""
      interval: 10
      timeout: 10