apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: App-2
  labels:
    f5cr: "true"
spec:
  host: app2.f5demo.cloud
  virtualServerAddress: "10.1.10.20"
  virtualServerName: "App-2"
  pools:
  - path: /
    service: svc-app1
    servicePort: 80
    monitor:
      type: http
      send: "GET /rn"
      recv: ""
      interval: 10
      timeout: 10
